// Copyright (C) 2026 rezky_nightky
// SPDX-License-Identifier: GPL-3.0-only

//! Per-cgroup process and connection detail (NIGHT-hunt-8).
//!
//! Owner problem: the BPF counters are per-cgroup, and on systemd
//! systems a whole user session shares ONE cgroup — so a monitor row
//! labeled "alacritty" (the first PID the identity walk happened to
//! see) can be carrying traffic generated by `curl`, `wget`, or
//! anything else launched inside that terminal. The row says
//! "alacritty"; the truth is "curl to 1.2.3.4:443". This layer closes
//! that gap userspace-only, with zero BPF changes: it joins the
//! kernel's own socket tables (/proc/net/{tcp,tcp6,udp,udp6}) with
//! per-PID file descriptors (/proc/<pid>/fd/*) and the cgroup
//! resolution from identity/.
//!
//! What it produces per cgroup:
//! - the total process count (the "(alacritty +3)" label suffix — a
//!   row that is more than one process stops lying by omission)
//! - every process holding a network socket, with its remote
//!   endpoints and states (the "eagle eyes" detail lines)
//!
//! NIGHT-boost-26 (per-endpoint byte attribution, the 2.4 frontier):
//! the walk now also resolves each held socket's kernel COOKIE —
//! pidfd_open(pid) + pidfd_getfd(pidfd, fd) + getsockopt(SO_COOKIE)
//! — so the monitor can join the BPF per-socket byte maps onto the
//! endpoint rows. The cookie is a kernel-generated u64, unique for
//! the socket's lifetime and never reused; the BPF observer keys its
//! per-socket counters by exactly that value. Discovery is
//! best-effort (a locked-down host or a kernel without pidfd_getfd
//! yields None and the endpoint rows simply carry no byte figures —
//! the /proc detail itself is unchanged), needs the same root the
//! monitor already runs under (CAP_SYS_PTRACE for foreign fds), and
//! rides the same 3s refresh TTL as the rest of the walk.
//!
//! Refresh cost is one /proc walk with an fd scan per PID — the same
//! class of work ss/netstat do — memoized behind a short TTL (3s) so
//! 1s monitor frames reuse the previous scan. All /proc failures are
//! best-effort: a stripped container simply yields no detail, never
//! an error, and the BPF counters keep flowing.

mod parse;

use std::collections::HashMap;
use std::fs;
use std::time::{Duration, Instant};

use crate::ebpf::identity::{pid_cgroup_id, pid_comm};
use crate::ebpf::loader::SocketBytes;

/// Default refresh TTL: detail lines tolerate 3s staleness — socket
/// churn is slower than the 1s byte counters, and the /proc+fd walk
/// is the expensive part.
const DEFAULT_REFRESH_TTL_SECS: u64 = 3;

/// Transport protocol a socket row was read from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Proto {
    Tcp,
    Udp,
}

/// One live socket endpoint, as the kernel sees it.
#[derive(Debug, Clone)]
pub struct SocketInfo {
    pub proto: Proto,
    /// Remote endpoint formatted for display ("142.250.191.78:443").
    pub remote: String,
    /// Kernel state name ("ESTABLISHED", "LISTEN", ...).
    pub state: &'static str,
    /// True when the socket had bytes sitting in tx/rx queues at scan
    /// time — the closest /proc gets to "this socket is moving".
    pub queued: bool,
    /// The socket's kernel cookie (NIGHT-boost-26): the join key for
    /// the BPF per-socket byte maps. None when discovery failed
    /// (pidfd_getfd refused, kernel without the syscall, or the
    /// socket table row was matched without an fd-side lookup).
    pub cookie: Option<u64>,
}

/// One process inside a cgroup that holds network sockets.
#[derive(Debug, Clone)]
pub struct ProcessDetail {
    pub pid: u32,
    pub comm: String,
    pub sockets: Vec<SocketInfo>,
}

/// Everything known about one cgroup's inhabitants.
#[derive(Debug, Clone, Default)]
pub struct CgroupConnections {
    /// Total processes living in this cgroup (label suffix material).
    pub total_procs: usize,
    /// Processes holding at least one socket, busiest first.
    pub socket_holders: Vec<ProcessDetail>,
}

/// Cached per-cgroup connection detail, refreshed behind a TTL.
#[derive(Debug)]
pub struct ConnectionMap {
    cache: HashMap<u32, CgroupConnections>,
    last_refresh: Option<Instant>,
    refresh_ttl: Duration,
    /// The per-frame per-socket byte join (NIGHT-boost-26): the
    /// monitor loop point-looks-up the BPF cookie maps for exactly
    /// the cookies the walk resolved and parks the result here —
    /// the renderers read it through [`ConnectionMap::socket_bytes`],
    /// so the join rides the SAME "everything known about one
    /// cgroup's inhabitants" structure the endpoint rows render
    /// from. Empty until the monitor's first successful join.
    socket_bytes: HashMap<u64, SocketBytes>,
}

impl Default for ConnectionMap {
    fn default() -> Self {
        Self::new()
    }
}

impl ConnectionMap {
    /// New empty map with the default 3s refresh TTL.
    #[must_use]
    pub fn new() -> Self {
        ConnectionMap {
            cache: HashMap::new(),
            last_refresh: None,
            refresh_ttl: Duration::from_secs(DEFAULT_REFRESH_TTL_SECS),
            socket_bytes: HashMap::new(),
        }
    }

    /// Install the per-frame per-socket byte join (NIGHT-boost-26):
    /// called by the monitor loop after every poll — the figures are
    /// live counters, refreshed each frame even when the /proc walk
    /// itself is TTL-cached. An Err from the loader side simply skips
    /// the install: the previous join's lifetime totals stay (stale
    /// by one frame, never fabricated-absent) — the same
    /// one-frame-tolerance contract the leaderboard's rows carry.
    pub fn apply_socket_bytes(&mut self, bytes: HashMap<u64, SocketBytes>) {
        self.socket_bytes = bytes;
    }

    /// The per-socket byte join (NIGHT-boost-26), keyed by socket
    /// cookie — the renderers' lookup table for endpoint figures.
    /// Absent cookie = no figures, never a fabricated zero.
    #[must_use]
    pub fn socket_bytes(&self) -> &HashMap<u64, SocketBytes> {
        &self.socket_bytes
    }

    /// Force a full refresh: read the socket tables, walk /proc, and
    /// rebuild the per-cgroup detail. Best-effort — unreadable parts
    /// of /proc are skipped, never fatal. Returns the number of
    /// cgroups with at least one socket holder.
    pub fn refresh(&mut self) -> usize {
        self.cache.clear();
        let sockets = read_socket_tables();

        let proc_entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(_) => {
                self.last_refresh = Some(Instant::now());
                return 0;
            }
        };

        for entry in proc_entries.flatten() {
            let name = entry.file_name();
            let Some(name_str) = name.to_str() else {
                continue;
            };
            let Ok(pid) = name_str.parse::<u32>() else {
                continue;
            };

            // Cgroup membership first: no point scanning fds for a
            // process whose cgroup we cannot resolve.
            let Some(cgroup_id) = pid_cgroup_id(pid) else {
                continue;
            };

            let entry = self.cache.entry(cgroup_id).or_default();
            entry.total_procs += 1;

            // fd scan: collect this PID's socket inodes, join with
            // the kernel socket table. NIGHT-boost-26: each MATCHED
            // socket also gets its kernel cookie resolved (pidfd_getfd
            // + SO_COOKIE) so the monitor's render pass can join the
            // BPF per-socket byte maps onto the endpoint rows. The
            // pidfd is opened lazily per PID — a process with no
            // matched socket never pays for it — and a failed open
            // (locked-down host, exotic kernel) marks the PID
            // cookie-less for the whole scan: no per-fd retry storm.
            let mut held: Vec<SocketInfo> = Vec::new();
            let mut pidfd: PidFd = PidFd::Untried;
            if let Ok(fds) = fs::read_dir(format!("/proc/{pid}/fd")) {
                for fd in fds.flatten() {
                    let Ok(target) = fs::read_link(fd.path()) else {
                        continue;
                    };
                    let Some(inode) = parse::parse_socket_fd(&target.to_string_lossy()) else {
                        continue;
                    };
                    if let Some(mut info) = sockets.get(&inode).cloned() {
                        if let Some(fd_num) = parse::parse_fd_number(&fd.file_name()) {
                            info.cookie = pidfd.cookie_for(pid, fd_num);
                        }
                        held.push(info);
                    }
                }
            }
            pidfd.close();

            if !held.is_empty() {
                // Endpoint order: established first, queued first.
                held.sort_by_key(|s| {
                    (
                        std::cmp::Reverse(s.state == "ESTABLISHED"),
                        std::cmp::Reverse(s.queued),
                    )
                });
                // Canonical comm boundary (NIGHT-optimized-1):
                // sanitize happens inside pid_comm() — comm is
                // attacker-controllable via prctl and this label flows
                // into the eagle-eyes detail lines of observe.
                let comm = pid_comm(pid).unwrap_or_else(|| format!("pid {pid}"));
                entry.socket_holders.push(ProcessDetail {
                    pid,
                    comm,
                    sockets: held,
                });
            }
        }

        // Process order within each cgroup: most sockets first, then
        // any-queued, then pid for determinism.
        for detail in self.cache.values_mut() {
            detail.socket_holders.sort_by_key(|p| {
                (
                    std::cmp::Reverse(p.sockets.len()),
                    std::cmp::Reverse(p.sockets.iter().any(|s| s.queued)),
                    p.pid,
                )
            });
        }

        self.last_refresh = Some(Instant::now());
        self.cache
            .values()
            .filter(|c| !c.socket_holders.is_empty())
            .count()
    }

    /// Refresh if the TTL has elapsed. Returns true if refreshed.
    pub fn maybe_refresh(&mut self) -> bool {
        let needs = match self.last_refresh {
            None => true,
            Some(last) => last.elapsed() >= self.refresh_ttl,
        };
        if needs {
            self.refresh();
            true
        } else {
            false
        }
    }

    /// Detail for one cgroup, if any is known.
    #[must_use]
    pub fn get(&self, cgroup_id: u32) -> Option<&CgroupConnections> {
        self.cache.get(&cgroup_id)
    }

    /// Total processes known to live in this cgroup (0 when unknown).
    #[must_use]
    pub fn proc_count(&self, cgroup_id: u32) -> usize {
        self.cache.get(&cgroup_id).map_or(0, |c| c.total_procs)
    }

    /// Total sockets held by this cgroup's processes (0 when unknown).
    #[must_use]
    pub fn socket_count(&self, cgroup_id: u32) -> usize {
        self.cache.get(&cgroup_id).map_or(0, |c| {
            c.socket_holders.iter().map(|p| p.sockets.len()).sum()
        })
    }

    /// Every distinct cookie the walk resolved (NIGHT-boost-26): the
    /// exact lookup set the monitor feeds to the loader's per-socket
    /// byte point-lookups — one entry per socket the /proc side
    /// knows, deduped (a shared socket table row can match several
    /// fds). Empty when no cookie resolved (graceful degradation,
    /// see [`PidFd`]).
    #[must_use]
    pub fn socket_cookies(&self) -> Vec<u64> {
        let mut out: Vec<u64> = Vec::new();
        for detail in self.cache.values() {
            for proc in &detail.socket_holders {
                for socket in &proc.sockets {
                    if let Some(cookie) = socket.cookie {
                        if !out.contains(&cookie) {
                            out.push(cookie);
                        }
                    }
                }
            }
        }
        out
    }

    /// Test seam: install synthetic per-cgroup detail (cross-module
    /// render tests and the frame benchmark build fixture maps
    /// without walking /proc).
    #[cfg(test)]
    pub fn insert(&mut self, cgroup_id: u32, detail: CgroupConnections) {
        self.cache.insert(cgroup_id, detail);
        self.last_refresh = Some(Instant::now());
    }

    /// Test seam: mutable access for per-frame fixture mutation (the
    /// frame benchmark toggles socket busy flags deterministically).
    #[cfg(test)]
    pub fn get_mut(&mut self, cgroup_id: u32) -> Option<&mut CgroupConnections> {
        self.cache.get_mut(&cgroup_id)
    }
}

// ── /proc walking helpers ───────────────────────────────────────────────────

// pid_cgroup_id and pid_comm live in identity/mod.rs as the ONE
// canonical /proc boundary (NIGHT-optimized-1): this walk, the
// identity walk, and the resolve_target match walk all route
// through them, so boundary fixes land once, not three times.

/// Per-PID pidfd state for cookie discovery (NIGHT-boost-26): a
/// tri-state so one failed `pidfd_open` (locked-down host, kernel
/// without the syscall) never re-triggers per fd — the PID is
/// cookie-less for the whole scan, the honest graceful degradation.
///
/// Deliberately `Copy` with NO Drop impl, the fd released by the
/// explicit `close()` after each PID's fd scan. The first cut had a
/// Drop impl calling a close() that ASSIGNED `*self = Untried` —
/// the assignment dropped the still-Open old value, whose Drop
/// called close() again: re-entrant drop recursion that overflowed
/// a 2MB test stack in 22ms on the CI runners (invisible locally —
/// no process in the dev container holds a matched socket, so the
/// pidfd never left Untried; the regression pin
/// `pidfd_close_on_open_fd_terminates` reproduces the overflow on
/// the broken shape and holds the fixed contract). A Copy enum with
/// no destructor makes every assignment in close() a plain store —
/// recursion is structurally impossible; the one leaked-fd window
/// (a panic mid-scan unwinding past the explicit close) is the
/// walk's best-effort class, an fd reclaimed at process exit.
#[derive(Clone, Copy)]
enum PidFd {
    Untried,
    Open(i32),
    Failed,
}

impl PidFd {
    /// Resolve one fd's socket cookie, opening the pidfd on first
    /// use. Returns None on any failure — cookie-less rows simply
    /// render without byte figures.
    fn cookie_for(&mut self, pid: u32, fd_num: i32) -> Option<u64> {
        // Open (or remember the failure) exactly once per PID.
        if matches!(self, PidFd::Untried) {
            *self = match unsafe { libc::syscall(libc::SYS_pidfd_open, pid as libc::pid_t, 0u32) } {
                fd if fd >= 0 => PidFd::Open(fd as i32),
                _ => PidFd::Failed,
            };
        }
        let PidFd::Open(pidfd) = *self else {
            return None;
        };
        // Duplicate the foreign fd into this process, read its
        // cookie, close the local copy — three syscalls, the price of
        // the join (there is no other userspace path from an inode or
        // a /proc row to a socket cookie).
        let local = unsafe { libc::syscall(libc::SYS_pidfd_getfd, pidfd, fd_num, 0u32) };
        if local < 0 {
            return None;
        }
        let mut cookie: u64 = 0;
        let mut len = std::mem::size_of::<u64>() as libc::socklen_t;
        let rc = unsafe {
            libc::getsockopt(
                local as i32,
                libc::SOL_SOCKET,
                libc::SO_COOKIE,
                std::ptr::addr_of_mut!(cookie).cast(),
                &mut len,
            )
        };
        unsafe { libc::close(local as i32) };
        if rc == 0 && len as usize == std::mem::size_of::<u64>() {
            Some(cookie)
        } else {
            None
        }
    }

    /// Release the pidfd, if one was opened.
    fn close(&mut self) {
        if let PidFd::Open(fd) = *self {
            unsafe { libc::close(fd) };
        }
        *self = PidFd::Untried;
    }
}

/// Read all four kernel socket tables into one inode-keyed map.
fn read_socket_tables() -> HashMap<u64, SocketInfo> {
    let mut out = HashMap::new();
    for (file, proto) in [
        ("/proc/net/tcp", Proto::Tcp),
        ("/proc/net/tcp6", Proto::Tcp),
        ("/proc/net/udp", Proto::Udp),
        ("/proc/net/udp6", Proto::Udp),
    ] {
        let content = match fs::read_to_string(file) {
            Ok(c) => c,
            Err(_) => continue, // udp6 etc. may be absent — fine
        };
        for line in content.lines().skip(1) {
            if let Some((inode, info)) = parse::parse_proc_net_line(line, proto) {
                out.insert(inode, info);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    /// Regression pin for the CI stack overflow (the 02284dd
    /// incident): closing a pidfd that holds an OPEN fd must
    /// terminate. The first cut's close() assigned `*self =
    /// PidFd::Untried` while Drop called close() — the assignment
    /// dropped the still-Open old value, whose Drop called close()
    /// again: re-entrant drop recursion, a 2MB stack gone in 22ms on
    /// the CI runners (locally invisible — no process here holds a
    /// matched socket, so the pidfd never left Untried). The Copy
    /// redesign makes the assignment drop nothing; this pin holds
    /// that contract by EXERCISING the close path on an Open fd.
    #[test]
    fn pidfd_close_on_open_fd_terminates() {
        let devnull = unsafe { libc::open(c"/dev/null".as_ptr().cast(), libc::O_RDONLY) };
        assert!(devnull >= 0, "the pin needs a real fd");
        let mut pidfd = PidFd::Open(devnull);
        pidfd.close();
        assert!(matches!(pidfd, PidFd::Untried));
        // Idempotent: a second close is a no-op.
        pidfd.close();
    }

    /// The map degrades gracefully when /proc is unreadable (returns
    /// empty, sets the refresh stamp — never panics).
    #[test]
    fn refresh_never_panics() {
        let mut map = ConnectionMap::new();
        let _ = map.refresh();
        assert!(map.last_refresh.is_some());
    }

    /// maybe_refresh honors the TTL contract (first call refreshes,
    /// immediate second does not).
    #[test]
    fn maybe_refresh_ttl() {
        let mut map = ConnectionMap::new();
        assert!(map.maybe_refresh());
        assert!(!map.maybe_refresh());
    }
}
