// Copyright (C) 2026 rezky_nightky
// SPDX-License-Identifier: GPL-3.0-only

//! Per-cgroup process and connection detail (NIGHT-hunt-8).
//!
//! Owner problem: the BPF counters are per-cgroup, and on systemd
//! systems a whole user session shares ONE cgroup — so a monitor row
//! labeled "alacritty" (the first PID the identity walk happened to
//! see) can be carrying traffic generated by `curl`, `wget`, or
//! anything else launched inside that terminal. The row says
//! "alacritty"; the truth is "curl to 1.2.3.4:443". This layer closes
//! that gap userspace-only, with zero BPF changes: it joins the
//! kernel's own socket tables (/proc/net/{tcp,tcp6,udp,udp6}) with
//! per-PID file descriptors (/proc/<pid>/fd/*) and the cgroup
//! resolution from identity.rs.
//!
//! What it produces per cgroup:
//! - the total process count (the "(alacritty +3)" label suffix — a
//!   row that is more than one process stops lying by omission)
//! - every process holding a network socket, with its remote
//!   endpoints and states (the "eagle eyes" detail lines)
//!
//! Refresh cost is one /proc walk with an fd scan per PID — the same
//! class of work ss/netstat do — memoized behind a short TTL (3s) so
//! 1s monitor frames reuse the previous scan. All /proc failures are
//! best-effort: a stripped container simply yields no detail, never
//! an error, and the BPF counters keep flowing.

mod parse;

use std::collections::HashMap;
use std::fs;
use std::time::{Duration, Instant};

use crate::ebpf::identity::resolve_cgroup_id_from_path;

/// Default refresh TTL: detail lines tolerate 3s staleness — socket
/// churn is slower than the 1s byte counters, and the /proc+fd walk
/// is the expensive part.
const DEFAULT_REFRESH_TTL_SECS: u64 = 3;

/// Transport protocol a socket row was read from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Proto {
    Tcp,
    Udp,
}

/// One live socket endpoint, as the kernel sees it.
#[derive(Debug, Clone)]
pub struct SocketInfo {
    pub proto: Proto,
    /// Remote endpoint formatted for display ("142.250.191.78:443").
    pub remote: String,
    /// Kernel state name ("ESTABLISHED", "LISTEN", ...).
    pub state: &'static str,
    /// True when the socket had bytes sitting in tx/rx queues at scan
    /// time — the closest /proc gets to "this socket is moving".
    pub queued: bool,
}

/// One process inside a cgroup that holds network sockets.
#[derive(Debug, Clone)]
pub struct ProcessDetail {
    pub pid: u32,
    pub comm: String,
    pub sockets: Vec<SocketInfo>,
}

/// Everything known about one cgroup's inhabitants.
#[derive(Debug, Clone, Default)]
pub struct CgroupConnections {
    /// Total processes living in this cgroup (label suffix material).
    pub total_procs: usize,
    /// Processes holding at least one socket, busiest first.
    pub socket_holders: Vec<ProcessDetail>,
}

/// Cached per-cgroup connection detail, refreshed behind a TTL.
#[derive(Debug)]
pub struct ConnectionMap {
    cache: HashMap<u32, CgroupConnections>,
    last_refresh: Option<Instant>,
    refresh_ttl: Duration,
}

impl Default for ConnectionMap {
    fn default() -> Self {
        Self::new()
    }
}

impl ConnectionMap {
    /// New empty map with the default 3s refresh TTL.
    #[must_use]
    pub fn new() -> Self {
        ConnectionMap {
            cache: HashMap::new(),
            last_refresh: None,
            refresh_ttl: Duration::from_secs(DEFAULT_REFRESH_TTL_SECS),
        }
    }

    /// Force a full refresh: read the socket tables, walk /proc, and
    /// rebuild the per-cgroup detail. Best-effort — unreadable parts
    /// of /proc are skipped, never fatal. Returns the number of
    /// cgroups with at least one socket holder.
    pub fn refresh(&mut self) -> usize {
        self.cache.clear();
        let sockets = read_socket_tables();

        let proc_entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(_) => {
                self.last_refresh = Some(Instant::now());
                return 0;
            }
        };

        for entry in proc_entries.flatten() {
            let name = entry.file_name();
            let Some(name_str) = name.to_str() else {
                continue;
            };
            let Ok(pid) = name_str.parse::<u32>() else {
                continue;
            };

            // Cgroup membership first: no point scanning fds for a
            // process whose cgroup we cannot resolve.
            let Some(cgroup_id) = pid_cgroup_id(pid) else {
                continue;
            };

            let entry = self.cache.entry(cgroup_id).or_default();
            entry.total_procs += 1;

            // fd scan: collect this PID's socket inodes, join with
            // the kernel socket table.
            let mut held: Vec<SocketInfo> = Vec::new();
            if let Ok(fds) = fs::read_dir(format!("/proc/{pid}/fd")) {
                for fd in fds.flatten() {
                    let Ok(target) = fs::read_link(fd.path()) else {
                        continue;
                    };
                    let Some(inode) = parse::parse_socket_fd(&target.to_string_lossy()) else {
                        continue;
                    };
                    if let Some(info) = sockets.get(&inode) {
                        held.push(info.clone());
                    }
                }
            }

            if !held.is_empty() {
                // Endpoint order: established first, queued first.
                held.sort_by_key(|s| {
                    (
                        std::cmp::Reverse(s.state == "ESTABLISHED"),
                        std::cmp::Reverse(s.queued),
                    )
                });
                let comm = fs::read_to_string(format!("/proc/{pid}/comm"))
                    .ok()
                    .map(|s| s.trim().to_string())
                    .unwrap_or_else(|| format!("pid {pid}"));
                entry.socket_holders.push(ProcessDetail {
                    pid,
                    comm,
                    sockets: held,
                });
            }
        }

        // Process order within each cgroup: most sockets first, then
        // any-queued, then pid for determinism.
        for detail in self.cache.values_mut() {
            detail.socket_holders.sort_by_key(|p| {
                (
                    std::cmp::Reverse(p.sockets.len()),
                    std::cmp::Reverse(p.sockets.iter().any(|s| s.queued)),
                    p.pid,
                )
            });
        }

        self.last_refresh = Some(Instant::now());
        self.cache
            .values()
            .filter(|c| !c.socket_holders.is_empty())
            .count()
    }

    /// Refresh if the TTL has elapsed. Returns true if refreshed.
    pub fn maybe_refresh(&mut self) -> bool {
        let needs = match self.last_refresh {
            None => true,
            Some(last) => last.elapsed() >= self.refresh_ttl,
        };
        if needs {
            self.refresh();
            true
        } else {
            false
        }
    }

    /// Detail for one cgroup, if any is known.
    #[must_use]
    pub fn get(&self, cgroup_id: u32) -> Option<&CgroupConnections> {
        self.cache.get(&cgroup_id)
    }

    /// Total processes known to live in this cgroup (0 when unknown).
    #[must_use]
    pub fn proc_count(&self, cgroup_id: u32) -> usize {
        self.cache.get(&cgroup_id).map_or(0, |c| c.total_procs)
    }

    /// Total sockets held by this cgroup's processes (0 when unknown).
    #[must_use]
    pub fn socket_count(&self, cgroup_id: u32) -> usize {
        self.cache.get(&cgroup_id).map_or(0, |c| {
            c.socket_holders.iter().map(|p| p.sockets.len()).sum()
        })
    }

    /// Test seam: install synthetic per-cgroup detail (cross-module
    /// render tests and the frame benchmark build fixture maps
    /// without walking /proc).
    #[cfg(test)]
    pub fn insert(&mut self, cgroup_id: u32, detail: CgroupConnections) {
        self.cache.insert(cgroup_id, detail);
        self.last_refresh = Some(Instant::now());
    }

    /// Test seam: mutable access for per-frame fixture mutation (the
    /// frame benchmark toggles socket busy flags deterministically).
    #[cfg(test)]
    pub fn get_mut(&mut self, cgroup_id: u32) -> Option<&mut CgroupConnections> {
        self.cache.get_mut(&cgroup_id)
    }
}

// ── /proc walking helpers ───────────────────────────────────────────────────

/// Resolve the cgroup ID (u32, BPF map key width) a PID lives in.
fn pid_cgroup_id(pid: u32) -> Option<u32> {
    let content = fs::read_to_string(format!("/proc/{pid}/cgroup")).ok()?;
    let path = content.lines().next()?.split("::").nth(1)?.trim();
    if path.is_empty() {
        return None;
    }
    let id64 = resolve_cgroup_id_from_path(&format!("/sys/fs/cgroup{path}"))?;
    Some(id64 as u32)
}

/// Read all four kernel socket tables into one inode-keyed map.
fn read_socket_tables() -> HashMap<u64, SocketInfo> {
    let mut out = HashMap::new();
    for (file, proto) in [
        ("/proc/net/tcp", Proto::Tcp),
        ("/proc/net/tcp6", Proto::Tcp),
        ("/proc/net/udp", Proto::Udp),
        ("/proc/net/udp6", Proto::Udp),
    ] {
        let content = match fs::read_to_string(file) {
            Ok(c) => c,
            Err(_) => continue, // udp6 etc. may be absent — fine
        };
        for line in content.lines().skip(1) {
            if let Some((inode, info)) = parse::parse_proc_net_line(line, proto) {
                out.insert(inode, info);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    /// The map degrades gracefully when /proc is unreadable (returns
    /// empty, sets the refresh stamp — never panics).
    #[test]
    fn refresh_never_panics() {
        let mut map = ConnectionMap::new();
        let _ = map.refresh();
        assert!(map.last_refresh.is_some());
    }

    /// maybe_refresh honors the TTL contract (first call refreshes,
    /// immediate second does not).
    #[test]
    fn maybe_refresh_ttl() {
        let mut map = ConnectionMap::new();
        assert!(map.maybe_refresh());
        assert!(!map.maybe_refresh());
    }
}
