// Copyright (C) 2026 rezky_nightky
// SPDX-License-Identifier: GPL-3.0-only

//! Eagle-eyes theme catalog (NIGHT-boost-18, improve-27): six
//! palettes the live monitor cycles with `t` — the cosmostrix
//! cycle contract (modulo wraparound), one key, zero config
//! (NIGHT-engrave-2 retired the uppercase `T` twin at the owner's
//! "better only simple 't'" call: forward-only, wrapping).
//!
//! Scope (the owner's exact task wording): themes live INSIDE the
//! eagle-eyes monitoring mode. The theme state is a process-global
//! atomic that NOTHING outside the monitor's key handler ever
//! writes — so every other surface (help, errors, status, list-apps)
//! always renders the default and the CLI's byte output is
//! unchanged. `netrunner` IS that default, and its encodings are
//! byte-identical to the pre-theme constants (the regression pin in
//! test/output/theme_tests.rs holds this).
//!
//! Each theme defines five semantic slots — brand, ok, warn, hot,
//! grey — and each slot carries all three capability encodings
//! (TrueColor RGB, xterm-256 index, 16-color SGR) plus their bold
//! twins, all generated by the `slot!` macro from the same numbers
//! docs/BRANDING.md documents.
//!
//! NIGHT-boost-23 (the masterclass audit of the five non-default
//! themes) pinned the fallback contract the table now follows:
//!
//! - **Nearest-match where hue must read true**: the 256-depth
//!   indices for brand/ok slots are the nearest xterm cube matches
//!   (forest's leaf-green brand had rendered olive, carbon's pale
//!   mint ok had rendered saturated spring green at 28x the error;
//!   carbon's silver brand had dimmed to the grey-ramp's 188 —
//!   below its own 16-color fallback's hierarchy). Warn/hot slots
//!   keep the documented visibility precedent: the saturated corner
//!   wins over the exact match when the hue family holds
//!   (netrunner warn 220 / hot 196 unchanged).
//! - **The grey slot degrades to the neutral grey ramp (245 / bright
//!   black 90) in every theme** — subordinate text stays subordinate
//!   whatever the accent becomes, a uniform-tier contract that
//!   outranks nearest-match.
//! - **16-color distinctness within a theme is absolute**: no two
//!   slots share an SGR (forest brand/ok both drew 32 — the brand
//!   now takes bright green 92; atomic brand/warn both drew 33 — the
//!   brand now takes bright yellow 93). The brand takes the bright
//!   slot so the frame's identity outranks its data on every
//!   legacy terminal.
//!
//! Catalog order is the cycle order:
//! netrunner (default) -> night_cyber -> forest -> spaceflight ->
//! carbon -> atomic -> netrunner.

use std::sync::atomic::{AtomicU8, Ordering};

use super::color::{capability, ColorCapability};

/// The monitor's themes, in cycle order. Index 0 is the default.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Theme {
    /// The default: purple brand #A855F7, the pre-theme constants.
    Netrunner,
    /// Neon night city: cyan brand #00E5FF, magenta-red champion.
    NightCyber,
    /// Deep woodland: leaf-green brand #7CB342, burnt-orange heat.
    Forest,
    /// Cool altitude: pale-sky brand #4FC3F7, teal-green status.
    Spaceflight,
    /// Near-mono industrial: silver brand #D6D6D6, minimal accents.
    Carbon,
    /// Retro lab bench: atomic orange #FF6D00, vivid status green.
    Atomic,
}

/// The whole catalog, in cycle order. The cycle surface is
/// monitor-only (ebpf) plus the catalog pins (test): a build without
/// the monitoring feature renders the default and never cycles.
#[cfg(any(feature = "ebpf", test))]
pub(crate) const THEMES: [Theme; 6] = [
    Theme::Netrunner,
    Theme::NightCyber,
    Theme::Forest,
    Theme::Spaceflight,
    Theme::Carbon,
    Theme::Atomic,
];

impl Theme {
    /// Cycle position (the index into [`THEMES`]).
    #[cfg(any(feature = "ebpf", test))]
    const fn index(self) -> u8 {
        match self {
            Theme::Netrunner => 0,
            Theme::NightCyber => 1,
            Theme::Forest => 2,
            Theme::Spaceflight => 3,
            Theme::Carbon => 4,
            Theme::Atomic => 5,
        }
    }

    /// Catalog name (lowercase, the BRANDING.md spelling) — rendered
    /// by the footer's status line (`theme netrunner`, NIGHT-engrave-2)
    /// so every `t` press names what the frame now wears.
    #[cfg(any(feature = "ebpf", test))]
    pub(crate) const fn name(self) -> &'static str {
        match self {
            Theme::Netrunner => "netrunner",
            Theme::NightCyber => "night_cyber",
            Theme::Forest => "forest",
            Theme::Spaceflight => "spaceflight",
            Theme::Carbon => "carbon",
            Theme::Atomic => "atomic",
        }
    }

    /// The theme's brand RGB triple (the BRANDING.md numbers) — the
    /// eagle-eyes border gradient's ramp source (NIGHT-boost-20):
    /// the frame's side rails interpolate down the brand's own
    /// dark-bright-dark wave.
    #[cfg(any(feature = "ebpf", test))]
    pub(crate) const fn brand_rgb(self) -> (u8, u8, u8) {
        match self {
            Theme::Netrunner => (168, 85, 247),
            Theme::NightCyber => (0, 229, 255),
            Theme::Forest => (124, 179, 66),
            Theme::Spaceflight => (79, 195, 247),
            Theme::Carbon => (214, 214, 214),
            Theme::Atomic => (255, 109, 0),
        }
    }
}

/// The semantic slots a theme paints. Hot and Grey exist only in
/// the full build and the pins: their color-layer builders are
/// ebpf-gated (the champion and subordinate tiers render solely
/// inside the monitor).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Slot {
    Brand,
    Ok,
    Warn,
    #[cfg(any(feature = "ebpf", test))]
    Hot,
    #[cfg(any(feature = "ebpf", test))]
    Grey,
}

/// All six encodings of one slot: three capabilities x regular/bold.
struct SlotEncodings {
    truecolor: &'static str,
    truecolor_bold: &'static str,
    color256: &'static str,
    color256_bold: &'static str,
    color16: &'static str,
    color16_bold: &'static str,
}

/// Build one slot's encodings from the BRANDING.md numbers: the
/// TrueColor escapes are derived from the same RGB the docs carry,
/// so the table and the documentation cannot drift apart silently.
macro_rules! slot {
    ($r:expr, $g:expr, $b:expr, $idx256:expr, $sgr16:expr) => {
        SlotEncodings {
            truecolor: concat!(
                "\x1b[38;2;",
                stringify!($r),
                ";",
                stringify!($g),
                ";",
                stringify!($b),
                "m"
            ),
            truecolor_bold: concat!(
                "\x1b[1;38;2;",
                stringify!($r),
                ";",
                stringify!($g),
                ";",
                stringify!($b),
                "m"
            ),
            color256: concat!("\x1b[38;5;", stringify!($idx256), "m"),
            color256_bold: concat!("\x1b[1;38;5;", stringify!($idx256), "m"),
            color16: concat!("\x1b[", stringify!($sgr16), "m"),
            color16_bold: concat!("\x1b[1;", stringify!($sgr16), "m"),
        }
    };
}

const fn table(theme: Theme, slot: Slot) -> SlotEncodings {
    match (theme, slot) {
        (Theme::Netrunner, Slot::Brand) => slot!(168, 85, 247, 135, 35),
        (Theme::Netrunner, Slot::Ok) => slot!(80, 250, 123, 84, 32),
        (Theme::Netrunner, Slot::Warn) => slot!(255, 235, 60, 220, 33),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Netrunner, Slot::Hot) => slot!(255, 59, 48, 196, 91),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Netrunner, Slot::Grey) => slot!(139, 139, 139, 245, 90),
        (Theme::NightCyber, Slot::Brand) => slot!(0, 229, 255, 51, 36),
        (Theme::NightCyber, Slot::Ok) => slot!(0, 255, 159, 49, 32),
        (Theme::NightCyber, Slot::Warn) => slot!(255, 200, 87, 221, 33),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::NightCyber, Slot::Hot) => slot!(255, 46, 99, 197, 91),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::NightCyber, Slot::Grey) => slot!(107, 122, 143, 245, 90),
        (Theme::Forest, Slot::Brand) => slot!(124, 179, 66, 107, 92),
        (Theme::Forest, Slot::Ok) => slot!(105, 240, 174, 85, 32),
        (Theme::Forest, Slot::Warn) => slot!(253, 216, 53, 220, 33),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Forest, Slot::Hot) => slot!(216, 67, 21, 166, 91),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Forest, Slot::Grey) => slot!(125, 139, 110, 245, 90),
        (Theme::Spaceflight, Slot::Brand) => slot!(79, 195, 247, 81, 36),
        (Theme::Spaceflight, Slot::Ok) => slot!(100, 255, 218, 86, 32),
        (Theme::Spaceflight, Slot::Warn) => slot!(255, 215, 64, 220, 33),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Spaceflight, Slot::Hot) => slot!(255, 82, 82, 203, 91),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Spaceflight, Slot::Grey) => slot!(144, 164, 174, 245, 90),
        (Theme::Carbon, Slot::Brand) => slot!(214, 214, 214, 231, 37),
        (Theme::Carbon, Slot::Ok) => slot!(170, 255, 178, 157, 32),
        (Theme::Carbon, Slot::Warn) => slot!(245, 197, 24, 220, 33),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Carbon, Slot::Hot) => slot!(255, 77, 77, 203, 91),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Carbon, Slot::Grey) => slot!(158, 158, 158, 245, 90),
        (Theme::Atomic, Slot::Brand) => slot!(255, 109, 0, 202, 93),
        (Theme::Atomic, Slot::Ok) => slot!(0, 230, 118, 42, 32),
        (Theme::Atomic, Slot::Warn) => slot!(255, 234, 0, 220, 33),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Atomic, Slot::Hot) => slot!(255, 23, 68, 197, 91),
        #[cfg(any(feature = "ebpf", test))]
        (Theme::Atomic, Slot::Grey) => slot!(176, 190, 197, 245, 90),
    }
}

/// The active theme state. Written ONLY by the eagle-eyes key
/// handler (`t` inside the alt screen); every other surface reads
/// the default and never knows themes exist.
static ACTIVE: AtomicU8 = AtomicU8::new(0);

/// The active theme.
pub(crate) fn active() -> Theme {
    match ACTIVE.load(Ordering::Relaxed) {
        1 => Theme::NightCyber,
        2 => Theme::Forest,
        3 => Theme::Spaceflight,
        4 => Theme::Carbon,
        5 => Theme::Atomic,
        _ => Theme::Netrunner,
    }
}

/// Set the active theme (the monitor's key handler only).
#[cfg(any(feature = "ebpf", test))]
pub(crate) fn set(theme: Theme) {
    ACTIVE.store(theme.index(), Ordering::Relaxed);
}

/// Pure cycle (the cosmostrix `cycle_color_scheme` contract): step
/// `dir` positions through the catalog with modulo wraparound in
/// both directions. Isolated so the wraparound math pins on its own;
/// the monitor only ever steps +1 since NIGHT-engrave-2 (one key),
/// and the negative direction stays available to the pins and any
/// future surface that needs it.
#[cfg(any(feature = "ebpf", test))]
#[must_use]
pub(crate) fn cycle_from(current: Theme, dir: i32) -> Theme {
    let n = THEMES.len() as i32;
    let idx = i32::from(current.index()) + dir;
    let wrapped = ((idx % n) + n) % n;
    THEMES[wrapped as usize]
}

/// Cycle the active theme one step (`+1` next, `-1` previous) and
/// return what it became.
#[cfg(any(feature = "ebpf", test))]
pub(crate) fn cycle(dir: i32) -> Theme {
    let next = cycle_from(active(), dir);
    set(next);
    next
}

/// The escape for one slot of one theme at one capability depth.
#[must_use]
pub(crate) fn escape_for(
    theme: Theme,
    slot: Slot,
    bold: bool,
    cap: ColorCapability,
) -> &'static str {
    let enc = table(theme, slot);
    match (cap, bold) {
        (ColorCapability::TrueColor, false) => enc.truecolor,
        (ColorCapability::TrueColor, true) => enc.truecolor_bold,
        (ColorCapability::Color256, false) => enc.color256,
        (ColorCapability::Color256, true) => enc.color256_bold,
        (ColorCapability::Color16, false) => enc.color16,
        (ColorCapability::Color16, true) => enc.color16_bold,
        (ColorCapability::Mono, _) => "",
    }
}

/// The escape for one slot of the ACTIVE theme at the probed
/// capability — the one entry point the color layer's builders call.
pub(crate) fn escape(slot: Slot, bold: bool) -> &'static str {
    escape_for(active(), slot, bold, capability())
}

// NIGHT-boost-18: the theme pins live under the single test/ tree
// (cosmostrix Pattern C), #[path]-wired across trees exactly like
// the eagle and footer pins.
#[cfg(test)]
#[path = "../../test/output/theme_tests.rs"]
mod theme_tests;
